#!/usr/bin/env python3
"""
Orchestrate quality matrix, outcome analyzer, and variance eval; aggregate JSON summaries;
emit actionable suggestions. With --apply, writes arctis/pipelines/enforcement.json so
prompt binding picks up extra guardrails (re-run matrix to verify).

  python scripts/pipeline_optimizer.py
  python scripts/pipeline_optimizer.py --apply
  python scripts/pipeline_optimizer.py --runs 30 --skip-variance
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

ENFORCEMENT_PATH = ROOT / "arctis" / "pipelines" / "enforcement.json"

DEFAULT_EXTRA_PREFIX = (
    "Follow the user task exactly. Prefer stable, concise answers. "
    "If you output JSON, use lowercase keys and no trailing commentary.\n\n"
)


def _run_script(rel: str, extra: list[str]) -> tuple[int, str]:
    cmd = [sys.executable, str(ROOT / rel), *extra]
    p = subprocess.run(cmd, cwd=str(ROOT), capture_output=True, text=True)
    out = (p.stdout or "") + (p.stderr or "")
    return p.returncode, out


def _load_report(path: Path) -> dict[str, Any] | None:
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None
    return data if isinstance(data, dict) else None


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Pipeline optimizer orchestrator")
    _default_matrix = ROOT / "arctis" / "pipelines" / "quality_test_matrix.json"
    ap.add_argument("--matrix", type=Path, default=_default_matrix)
    ap.add_argument("--runs", type=int, default=30)
    ap.add_argument("--skip-variance", action="store_true")
    ap.add_argument("--skip-analyzer", action="store_true")
    ap.add_argument("--apply", action="store_true", help=f"Write {ENFORCEMENT_PATH}")
    ap.add_argument(
        "--output",
        type=Path,
        default=ROOT / "reports" / "pipeline_optimizer_summary.json",
    )
    args = ap.parse_args(argv)

    matrix_out = ROOT / "reports" / "pipeline_quality_matrix_report.json"
    var_out = ROOT / "reports" / "pipeline_variance_report.json"
    ana_out = ROOT / "reports" / "pipeline_outcome_analysis.json"

    steps_log: list[dict[str, Any]] = []

    code, log = _run_script(
        "scripts/pipeline_quality_matrix.py",
        ["--matrix", str(args.matrix), "--output", str(matrix_out)],
    )
    steps_log.append({"step": "quality_matrix", "code": code, "log_tail": log[-2000:]})

    if not args.skip_analyzer:
        c2, log2 = _run_script(
            "scripts/pipeline_outcome_analyzer.py",
            ["--output", str(ana_out)],
        )
        steps_log.append({"step": "outcome_analyzer", "code": c2, "log_tail": log2[-2000:]})

    if not args.skip_variance:
        c3, log3 = _run_script(
            "scripts/pipeline_variance_eval.py",
            [
                "--matrix",
                str(args.matrix),
                "--runs",
                str(args.runs),
                "--output",
                str(var_out),
            ],
        )
        steps_log.append({"step": "variance_eval", "code": c3, "log_tail": log3[-2000:]})

    q = _load_report(matrix_out)
    v = _load_report(var_out)
    a = _load_report(ana_out)

    suggestions: list[str] = []
    if q:
        pr = float(q.get("summary", {}).get("pass_rate", 0.0))  # type: ignore[union-attr]
        if pr < 1.0:
            suggestions.append(
                f"Quality matrix pass_rate={pr:.2f}: review failed cases in {matrix_out.name}."
            )
    if v:
        for row in v.get("cases", []) if isinstance(v.get("cases"), list) else []:
            if not isinstance(row, dict):
                continue
            if float(row.get("output_hash_unique_ratio", 0.0)) > 0.15:
                suggestions.append(
                    f"Variance: case {row.get('case_id')} unstable outputs — enforce temperature=0 "
                    "and structured prompts."
                )
    if a:
        suggestions.extend([str(s) for s in a.get("suggestions", []) if isinstance(s, str)])
    if v:
        suggestions.extend([str(s) for s in v.get("suggestions", []) if isinstance(s, str)])

    dedup: list[str] = []
    seen: set[str] = set()
    for s in suggestions:
        if s not in seen:
            seen.add(s)
            dedup.append(s)

    apply_actions: list[str] = []
    if args.apply:
        ENFORCEMENT_PATH.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "version": 1,
            "updated_at": datetime.now(UTC).isoformat(),
            "additional_prefix": DEFAULT_EXTRA_PREFIX,
            "notes": "Generated by scripts/pipeline_optimizer.py --apply",
        }
        ENFORCEMENT_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        apply_actions.append(f"wrote {ENFORCEMENT_PATH}")

    summary = {
        "generated_at": datetime.now(UTC).isoformat(),
        "matrix_report": str(matrix_out),
        "variance_report": str(var_out),
        "analyzer_report": str(ana_out),
        "subprocess_steps": steps_log,
        "aggregated_suggestions": dedup,
        "apply_actions": apply_actions,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")
    print(f"Wrote {args.output}")
    worst = 0
    for row in steps_log:
        worst = max(worst, int(row.get("code", 0)))
    return worst


if __name__ == "__main__":
    raise SystemExit(main())
